[project]
name = "gemini-json-ocr"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12.0"
dependencies = [
    "python-dotenv",
    "google-genai",
    "pydantic"
]

[dependency-groups]
dev = [
    "ruff"
]
